### ISSUE TITLE
Platform Monitoring Setup - POC

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1042]
**Describe the issue**
Initial exploration of platform monitoring setup. We need dashboards that shows platform healthiness, as well as resource condition.

**Definition of done**
- [x] get a list of important platform metrics to monitor (service endpoints or processes)
- [x] setup sysdig dashboard - for all clusters
- [x] setup Uptime robot for platform liveness check - test in silver and klab
- [x] setup Cerberus - test in klab

**Comment by mitovskaol** [comment]
@ShellyXueHan The 5 essential Openshift services that are required to be monitored have already been identified and documented [here](https://miro.com/app/board/o9J_kgyjm_k=/)

The iteration #1 of the uptime robot dashboard will include monitoring the Openshift API service only as documented [here](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/828)

**Comment by ShellyXueHan** [comment]
Here are some updates after some Cerberus test setup:

### Things done:
- setup Cerberus on Klab
- verified prometheus connection issue is intermittent (might be related to apporeto), currently looking good
- setup Uptime Robot for Cerberus endpoint https://stats.uptimerobot.com/w28pPSLlZE

### Next step:
- test setup Cerberus on silver (see how it behaves on busy cluster)
- if things go well, update Uptime Robot for silver cluster
- work on CCM for cerberus
- create documents

### Some things to consider:
- look into Nagios API for exporting alerts/metrics to be consumed by Cerberus/Uptime bot
- Gerald mentioned that Cerberus is aggressive on pod failure events (false alarm), so we should look into replacing `watched namespaces` with `custom checks`: https://github.com/cloud-bulldozer/cerberus#bring-your-own-checks
- if Cerberus does not fit our cas, consider build an API app aggregating metrics from other platform monitoring tools
- Steven mentioned a monitoring idea of running a cronjob for application build-deployment-testing, which would be helpful to test on common actions that app teams do on the platform
- limit of dashboard on Uptime bot is 50, we should have 1 dashboard per cluster, and 1 dashboard per platform shared service

**Comment by ShellyXueHan** [comment]
POC worked with Cerberus and uptime bot setup in klab. Closing
