### ISSUE TITLE
Develop the OCP 3-> OCP 4 Migration Sweep Plan

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1098]
There are about 65 apps still remaining in OCP 3.11 as of April 8. These applications will migrated to OCP 4.5 as part of the "sweep" phase of the migration using the Container Migration Tool provided by RedHat that allows migrating a number of application at once (mass-migration).

DoD:
- [x] Pick a date of the mass-migration
- [x] Finalize the migration plan e.g. what happens on the date of the migration and identify the prep work that needs to happen before that.
- [x] Finalize [the comms](https://drive.google.com/file/d/144ei0jDpgI4KeJ9oPoq4sagzV_CJN71f/view?usp=sharing) and send out to the remaining OCP 3 teams 
- [x] Book an orientation meeting with the remaining OCP 3 product teams
- [x] Send out a meeting invite for the "sweep" day
- [x] Confirm the team's availability to test on the "sweep" day

**Comment by mitovskaol** [comment]
We found that almost all teams have started their migrations and are in-flight right now which makes them ineligible for automated migration using Redhat's migratiton tool. Jason will continue working with each team individually and will use the tool for those who are eligible.
