### ISSUE TITLE
Roadmap Execution: Run Roadmap Planning Workshops

### ISSUE THREAD

**Issue by juhewitt** [BCDevOps/developer-experience#1160]
**Describe the issue**
Complete 1 year in review and 4 workshops over the span of 3 days.

**Additional context**
From May 11th to May 13th, there will be 1 year in review and 4 workshops, each session 2 hours.  The Workshops will lead to deliverables in Mural boards which can be converted to product roadmaps.

- [ ] Reflecting on the Previous Year
- [ ] Workstream: Making our service easier to understand and use
- [ ] Workstream: Community engagement and support
- [ ] Workstream: Increasing security across platform apps
- [ ] Workstream: Mainting operational excellence, reliability and monitoring

**Definition of done**
Year In Review and Workshops are completed, with deliverables that will lead to product roadmaps implemented with ZenHub Epics for 2021/2022 fiscal.
