### ISSUE TITLE
SG - Archeobot Multicluster Prep

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#1246]
- [x] move to new repo
- [x] upgrade version and make full use of upgrade features
- [x] apply justin's recommendations for easing stress on the operator
- [x] apply artifactory url format change (+ nginx)
