### ISSUE TITLE
Update Registry NATS Payload

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1274]
**Describe the issue**
NATS Payload is currently missing important information for provisioning vault access. The payload could also use some enhancements and optimizations to both improve data quality, enable multiple technical contacts in the future, and to decrease the time it takes for the provisioner to generate the manifests for the project set.

**Additional context**
A 1 hour design discussion is required for this task to define the new payload format and gather the data requirements 

**Definition of done**
- [x] Design defined and documented
- [ ] API Changes Implemented
- [x] Provisioner Changes Implemented
- [ ] Functionality verified between Registry and Provisioner

**Comment by j-pye** [comment]
YAML Gist: https://gist.github.com/j-pye/02c3bb929db4f49afc6f66571b00941c
JSON Gist: https://gist.github.com/j-pye/c63934e389f0b3378fd5edc770630ac4

**Comment by j-pye** [comment]
Updated gists:
- YAML Gist: https://gist.github.com/j-pye/02c3bb929db4f49afc6f66571b00941c
- JSON Gist: https://gist.github.com/j-pye/c63934e389f0b3378fd5edc770630ac4
