### ISSUE TITLE
Document requirements for Platform's Content Management System

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1349]
This ticket lists the requirements for the Content Management System for the Platform documentation.

- **GitHub integration and ability to pull content from multiple repos** - most our technical docs are stored in GitHub repos alongside the source code as markdown files, we want to be able to pull them from there into a doc portal where they will be laid oud in a more presentable way. Need to have an easy way to trigger the refresh of doc copies in the portal when the source in GitHub changes
- **Searchability**  - we need to have robust search engine 
- Easy to use interface to organizing content and the layout
- **IMPORTANT: Support user authentication via KeyCloak SSO for protected content (what Documize does for us now)**
- **Easy to contribute** - Support for Community Contributed Content as described [in this ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/devhub-app-web/523)

**Comment by sbathgate** [comment]
An option I felt could merit consideration is called [Notion](https://www.notion.so/enterprise). While it is a closed source project it does meet a lot of the above requirements including:
- [X] SSO Integration (Enterprise only)
- [X] Integrated and effective search capability
- [X] Public and Private views (Granular to an individual user, group or domain)
- [X] Advanced permissions (Read Only, Edit, Owner etc)
- [X] Has a developing API that can update documentation from GitHub repos
- [X] Enterprise support capability

A few extra things it can do:
- export groups/all docs as a pdf for compliance and audit needs
- expansive template guides for all kinds of documentation needs (meeting notes, design sessions, roadmapping etc)
- Search results show the breadcrumb trail
- Multiple ways to view and organize data
