### ISSUE TITLE
Archeobot Multicluster Development

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#1351]
**Describe the issue**
Archeobot needs to be installed on a namespace separate from Artifactory - this will allow Archeobot to be installed across multiple clusters and connect to an Artifactory service that may be on a separate cluster.

**Additional context**
This task mostly involves re-writing existing Archeobot content and requires considerable testing.

**Definition of done**
- [x] development work on permissions changes completed
- [x] development work on namespace changes completed
- [x] testing in KLAB completed
- [x] permissions testing completed
- [x] documentation on the upgrade path in silver
- [x] upgrade in silver
