### ISSUE TITLE
Create alignment with Cloud Pathfinder roadmap

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1421]
**Describe the issue**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [ ]  a document that has both roadmaps
- [ ]  slide deck for Hayden
- [ ] a consolidated message that defines what Platform services team and Cloud Pathfinder working on
