### ISSUE TITLE
Artifactory Projects Implementation

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#1480]
**Describe the issue**
Previously, we had planned to roll out access to private repositories to teams directly. However, since the new Projects feature is available in Artifactory, we are planning to change our rollout so that teams request projects directly, and then have access to private repos via projects. This will make administration much easier for us.

**Definition of done**
- [x] Artifactory is upgraded to a version which includes Projects
- [x] The operator is upgraded to include a request for a Project (if appropriate)
- [x] The possibility of integration with the registry has either been actioned or rejected.
- [ ] Use of projects is fully documented.
