### ISSUE TITLE
Artifactory Xray Implementation

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#1481]
**Describe the issue**
Implement Xray in Artifactory.

**Definition of done**
- [x] Xray installation scripts written and tested.
- [x] Xray design plan documented.
- [x] Any required integrations with the operator implemented.
- [x] Any changes to Artifactory configuration recorded and integrated into pipeline/install scripts
- [x] All documentation created
