### ISSUE TITLE
Artifactory Projects Functionality

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#1619]
**Describe the issue**
This sprint goal is going to cover the rollout of access to Artifactory Projects for teams.

**Definition of done**
- [ ] Projects functionality is designed
- [ ] Projects functionality is implemented and tested in KLAB
- [ ] Teams have access to Projects in Silver
- [ ] Use of Projects is fully documented
