### ISSUE TITLE
Mobile Signing - migrate team to new way of signing

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1751]
**Describe the issue**
As discussed, we are all good to use the new way of signing for iOS and Android apps.

**Definition of done**
- [ ] message put up onto MSS
- [ ] start involve a team for testing
- [ ] gather contact info from each team

**Details**

For each app team, we will walk through the following steps:
- connect with team and schedule on change
- onboarding meeting and kick off migration
- support team with issues/questions
- confirm migration complete
- update our mobile app registry in Documize

**App teams:**
- [x] BC Vaccine Card Verifier
- [x] MyHealthBC
- [x] BCVV and provider
- [x] WorkBC
- [x] Invasive Species
- [x] BC Secure Wallet
- [x] BC Service Card and video app
- [x] EForWasteBC
- [x] Moose Tracker
- [x] MyRangeBC and dashboard (maybe not in use)
- [x] Inspect (TBD)
- [x] iSpecies Goshawk
- [x] BC Health Service Locator
- [x] COVID-19 Support
- [x] BC Parks
- [x] Wildfire Service

Note: enterprise apps not listed for security reason

**Comment by ShellyXueHan** [comment]
completed!
