### ISSUE TITLE
STRA for GitHub Enterprise

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1792]
Complete STRA for GitHub enterprise for use by Platform Services team and select Ministry partners

- [x] Document architecture
- [x] Document intended use
- [x] Document Risks
- [x] Ensure compliance w/ Cloud Security Schedule
- [x] Create SoAR
- [x] Review and Sign-off
