### ISSUE TITLE
STRA for Stack Overflow

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1836]
- [x] Document architecture
- [x] Document intended use
- [x] Document Risks
- [x] Ensure compliance w/ Cloud Security Schedule
- [x] Create SoAR
- [x] Review and Sign-off
