### ISSUE TITLE
Platform Services Supported Applications Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1878]
**Describe the issue**
To ensure proper support and response of our support applications, essential monitoring and alerting within Sysdig is necessary. There are a variety of methodologies to achieve this. For our teams needs, this will be broken into up to three distinct phases. 

- Baseline monitoring which focuses on Saturation. This will include CPU/Memory/Storage monitoring and alerting. 
- Enhanced monitoring, which are more unique to the application but could include metrics along these lines:
  - Traffic Monitoring:
    - Number of HTTP Requests
    - Number of Sessions
    - Number of Transactions per second
  - Errors:
    - Rate of Failed Requests
  - Latency:
    - Amount of time to service requests
- Uptime monitoring, f deemed necessary (24/7 support applications for example.

**Definition of done**
When all of the Platform Services applications below have at least the Baseline Montoring/Alerting Configurations setup.

- [ ] AI OPS/Resource Tuning Advisor App
- [x] AQUA
- [x] ArgoCD (Shared)
- [x] Artifactory
- [ ] CCM (Platform Services ArgoCD)
- [ ] DevHub
- [x] Documize
- [ ] EnterpriseDB Operator
- [ ] Just Ask!
- [ ] OCP 4 Project Registry
- [ ] OCP4 Provisioner
- [ ] Platform Services Comms Subscription Service (Mautic)
- [ ] Rocket.Chat & Reggie & Hubot (BCBot)
- [ ] Vault

The following applications are currently excluded from this requirement:
- Devops-Requests Requestron
- KeyCloak SSO & Realm-o-matic (EXTERNAL)
- "Mobile Signing Service" (Is this an app within the cluster?)
- Platform Essential Services Monitoring
- Repo-Mountie
- Sysdig Monitoring Service

**Comment by w8896699** [comment]
CPU Used vs Requested(Utilization) where it the percentage between sysdig_container_cpu_cores_used and kube_pod_sysdig_resource_requests_cpu_cores. We can learn how much resources the registry is actually using vs how much it requested
CPU Used vs Limited(Threshold) where is the percentage between sysdig_container_cpu_cores_used and kube_pod_sysdig_resource_limits_cpu_cores. We can learn how much more resources is available for the registry application
For Utilization, we would like to achieve as much high as possible. However, its not always achievable 80% or above, but we will try our best.
For Limitations, I have set up an alert so when its 80%, it will send a rc message to registry internal channel to notify us to give it more resources as it almost run out of the resources. we can then give it more resources or do Horizontal auto scale depends on the situation.

**Comment by ShellyXueHan** [comment]
@w8896699 somethings to consider when you start to work on enhanced monitoring is to look at the service golden signal. Here is a sample dashboard for your reference: https://app.sysdigcloud.com/#/dashboards/108997?last=3600 (in the `Platform Experience` sysdig team). There is also a Sysdig template called `Workload Status & Performance` in each sysdig team that might be of your interest. These two have some panels in common, would be great if you can combine the useful ones into one dashboard. Anyway, I'll leave it up to you to decide if you'd like to implement it at the same time when you work on the baseline ones or tackle it later on!
