### ISSUE TITLE
Prevent use of unsupported service types in OCP

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1899]
**Describe the issue**
The F5 CIS operator generates ERROR logs due to the presence of LoadBalancer type service objects. Some investigation shows some teams also have NodePort services. Neither of these are supported in our cluster. Teams should instead use ClusterIP type for their services.

Likely most of these are coming from Helm or Kustomize templates from 3rd parties.

We can set a quota of zero for both NodePort and LoadBalancer services in all customer namespaces via the Project Registry.

**Additional context**
- https://discuss.kubernetes.io/t/disable-service-type-loadbalancer/4660
- https://kubernetes.io/docs/concepts/policy/resource-quotas/

**Definition of done**
- [x] Draft code for Project Registry to add new quotas
- [x] Pick a date for rollout
- [x] Find all namespaces with affected services and email them with the deadline of when the quota will be added
- [x] Support teams as needed through the transition
- [x] Apply new quotas to all namespaces

**Comment by StevenBarre** [comment]
All tasks completed!
