### ISSUE TITLE
Platform Uptime Tool Migration

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1908]
**Describe the issue**
migrate our platform service status page from UptimeRobot to a better tool!

**Definition of done**
- [x] explore alternatives and compare
- [x] select the best alternative - `Uptime.com`
- [ ] STRA
- [x] migrate monitors from Uptime Robot to the selected tool
- [x] setup alerts in the selected tool
- [x] config team access
- [x] update doc

**Comment by mitovskaol** [comment]
Work on the STRA for uptime.com will be tracked in a separate ticket as part of the Security workstream.
