### ISSUE TITLE
Scale down CloudGuard and Re-install ACS Operator on KLAB

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2178]
In order to decide on Aqua > ACS switch, we need another look at ACS in KLAB.
Since CloudGuard is currently running, we're hoping to scale it down and re-install the ACS operator.  We would like to keep CloudGuard installed as we will likely need to do more testing with it in future.

**Tasks:**
- [x] scale down pods in the bcgov-checkpoint namespace in KLAB to 0 -> Decided to remove
- [x] schedule time w/ Gerald to setup ACS
- [x] install operator for ACS
https://docs.openshift.com/acs/3.67/installing/install-ocp-operator.html
- [x] ensure appropriate test license/creds applied to Stackrox namespace

Setup of SSO will be done as a separate task by Shelly/Nick

**Comment by NickCorcoran** [comment]
Checkpoint indicated that enforcer agents and AC need to be disabled as well as scaling down pods.  I have asked for specific instructions on doing this, and also an uninstallation script.

**Comment by StevenBarre** [comment]
Removed CloudGuard via helm per https://sc1.checkpoint.com/documents/CloudGuard_Dome9/Documentation/Assets/Kubernetes.htm?tocpath=Assets%7COnboarding%7C_____4

**Comment by StevenBarre** [comment]
Taking the time to create the needed automation in CCM to install ACS into multiple clusters instead of doing it by hand.

**Comment by StevenBarre** [comment]
>Setup of SSO will be done as a separate task by Shelly/Nick

Automated this as part of CCM

ACS is installed with Central in KLAB and both KLAB and CLAB reporting data.
