### ISSUE TITLE
OCP 4.8 SILVER Upgrade

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2222]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.8.

**Additional context**

**Definition of done**
- [x] Execute RFC for Registry Hard Prune.
- [x] Execute RFC for OCP upgrade and firmware updates.
- [x] SILVER upgraded to OCP 4.8.

**Comment by wmhutchison** [comment]
SILVER now upgraded.
