### ISSUE TITLE
Vault Access Setup

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#2227]
**Describe the issue**
Me and Shelly need admin access to vault and also we (platform service and DXC) need a namespace to put secrets and stuff.

**Definition of done**
- [x] Terraform config set up for Shelly/Cailey's view access to all the files in Vault.
- [x] Shelly/Cailey need to be able to generate new root tokens for admin tasks.
- [x] Namespace set up for team secrets -> we have platteam mount paths (role) setup now instead of a namespace
- [x] Team access to new namespace.
- [x] Should DXC have a namespace of their own too, or just the shared one for the whole platform team? -> DXC have their own secret management system.
