### ISSUE TITLE
Tracking issues with Red Hat involving OCP 4.8 upgrade in SILVER | SPIKE

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2233]
**Describe the issue**
Will post a summary and top-level updates here as we continue working with Red Hat regarding upgrading the SILVER cluster to OCP 4.8.

**Additional context**
https://access.redhat.com/support/cases/#/case/03146251
https://github.com/BCDevOps/openshift-wiki/blob/master/docs/HowTo/UpdatePatroni.md (current Patroni upgrade instructions to fix errant health check scripts)

**Workarounds**
- [x] Technical work around at present is to remove old lock files on all APP nodes where an Aqua agent is present.
- [x] Business work-around for Patroni stability issues requires all stakeholders to upgrade to a specified version of Patroni and create PDBs. Users have been given until March 4th to complete this, and a new RFC created/approved to resume work on March 7th.

**Definition of done**
- [x] Continue working with Red Hat as needed to feed them data and assist in troubleshooting
- [x] Test out any work-arounds that are identified to help us reliably complete the OCP 4.8 upgrade in SILVER

**Comment by wmhutchison** [comment]
An earlier hack is in place in SILVER as well as CLAB/KLAB which is a cronjob running on the UTIL servers for each cluster, that every hour will SSH into upgraded nodes and restart kubelet services. While Red Hat assures this is not an impactful thing to do, it's not normal to be doing this to what amounts to the local "brain" for each node we're doing this for (9-10 out of 44 nodes in SILVER, and all CLAB/KLAB nodes).

For now we will keep status quo because upgrading has been paused in SILVER by virtue also of other stakeholders working on some Patroni upgrades that are first needed to improve the stability of Patroni clusters. Once that blocker is removed, we have both a workaround and more official means of moving forward with SILVER upgrade.

Next week stakeholders responsible for Aqua will pursue a vendor ticket on the matter to determine why Aqua is creating so many "lock" files in /var/log/pods/<aqua-agent> on the affected nodes.

**Comment by wmhutchison** [comment]
Ongoing investigations into this issue continues. Yesterday Platform Ops had a Zoom call with Aqua support/engineers on the matter. Some follow-up data dump requests for agent logs from a single active node with higher levels was requested and fulfilled by Steven Barre.

Further investigation by Steven Barre and Matt Robson revealed that the current symtpom of what is going on is that the Aqua scanner pods are starting up their own containers via direct calls to crio instead of asking Openshift via API to do it. This has been successfully replicated by Matt Robson in his own Openshift environment. He's taking this observation away for the crio folks in Red Hat to see if this is expected behaviour and what if anything can be done from the side of Openshift on the matter.

**Comment by wmhutchison** [comment]
Moving into Sprint Backlog for now, all current action plans have been solidified, barring any new results from the Aqua ticket.

**Comment by wmhutchison** [comment]
Will promote back to In Progress now that this work can proceed and will proceed on March 7th. Will update/close if there is nothing new to add to the ticket in terms of take-away from remaining upgrade work.
