### ISSUE TITLE
OCP 4.8 GOLD Upgrade

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2248]
**Describe the epic**
Epic to track all work upgrading GOLD to OCP 4.8.

**Additional context**

**Definition of done**
- [x] Execute RFC for OCP upgrade prep (CHG0034387 on March 20th).
- [x] Execute RFC for OCP upgrade (CHG0034391 on March 21st).
- [x] GOLD upgraded to OCP 4.8.
