### ISSUE TITLE
OCP 4.8 GOLDDR Upgrade

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2252]
**Describe the epic**
Epic to track all work upgrading GOLDDR to OCP 4.8.

**Additional context**

**Definition of done**
- [x] Execute RFC for OCP upgrade prep (CHG0035289 on March 27th 2022).
- [x] Execute RFC for OCP upgrade (CHG0035295 on March 28th 2022).
- [x] GOLDDR upgraded to OCP 4.8.
