### ISSUE TITLE
API Compatibility Issues between Openshift 4.8 and 4.9

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2256]
**Describe the issue**
After we upgrade to Openshift 4.8, AlertManager will start giving the Platform Operations team notifications regarding Kubernetes resources that need its API definition to be updated before an upgrade to Openshift 4.9 can be tendered. This EPIC will track efforts spent towards each cluster as we investigate and either deal with such compatibility issues ourselves internally if managed by us, or otherwise notifying stakeholders to do the same.

**Additional context**
https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html#ocp-4-9-removed-kube-1-22-apis
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22
https://access.redhat.com/articles/6329921

**Definition of done**
- [ ] All clusters that have been upgraded to OCP 4.8 have received evaluations for matching API calls needing remediation
- [ ] All remediation efforts that are internal (Platform Ops and Services teams) are completed.
- [ ] All remediation efforts requiring developer intervention has confirmed to be finished.
- [ ] Final confirmation that all clusters are agreed upon to be in an upgradable state to OCP 4.9

**Comment by wmhutchison** [comment]
The Red Hat Solutions article focusses mainly on checking out invocations of the noted Kubernetes resources with the offending version (v1beta1), but we need to also ensure we're actively auditing the existence of actual K8S resources that have this version as well, since some of those resources might otherwise slip underneath the radar for being checked.
