### ISSUE TITLE
GitHub Enterprise KeyCloak Integration investigation

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2271]
In order to better control access to GitHub Enterprise resources, we plan to integrate our KeyCloak SSO service to broker connections from GitHub and Azure AD (IDIR w/ MFA).  
The SAML configuration is done at the organization level with the enterprise, or globally at the enterprise root.  We will be testing at the organization level.

**Tasks to Complete:**
- [x] create test org in enterprise
- [x] create client in KeyCloak realm
- [x] Setup saml sso
- [x] test with GitHub and IDIR (via Azure AD) IDs

**Definition of done:**
- [x] Can login with GitHub account (in BCGov or BCDevOps org) that has been granted access
- [x] Can login with IDIR (via Azure AD)

**Comment by mitovskaol** [comment]
@NickCorcoran Please connect with @ll911 who found that 1) GHE SSO only works with SAML not OIDC, and 2) current SAML offered by IDIM is via siteminder and he found that the SAML with current version siteminder does not work with GH. So this ticket might be a no-go at this moment.

**Comment by NickCorcoran** [comment]
I was able to get SSO setup w/ SAML.  We used the same realm as OpenShift login that uses GitHub or Azure AD (IDIR).  This avoids the Siteminder block.

**Comment by ll911** [comment]
@NickCorcoran so are you using the SAML provided by keycloak? that should work, can you share the group mapping for saml? would like to limit to subset of group instead of all authed users.

**Comment by NickCorcoran** [comment]
Sure, @ll911, I'll send you details in on RC.

**Comment by NickCorcoran** [comment]
Initially created linkage to realm with GitHub and IDIR (Azure AD) IDPs.  As we only want IDIR as SSO call-back for this purpose, linking to the Azure AD realm only is more appropriate.  
A client will need to be setup there where SAML groups would be assigned.  As this is a high level realm, giving others ability to create groups/assignments here might not be the best approach.  This could become a heavy administration for those managing IDIR > GitHub group assignments.  Will try this approach out next sprint, but will also investigate direct connection to Azure AD and assignment of SAML assertions as part of groups.  
Instructions on how to setup direct connect to Azure AD can be found here:  https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/github-tutorial  This requires creation of an Enterprise Application in the Azure AD that will require ADMS assistance in setting up.
