### ISSUE TITLE
Mitigate Risk identified in Mautic STRA 

### ISSUE THREAD

**Issue by bruce-wh-li** [BCDevOps/developer-experience#2301]
- [ ] Use SAN Certificate instead of Wildcard Cert
- [ ] Use Platform Vault service to store secrets
- [ ] Create a procedure to regularly audit Mautic's user and role setting 
- [ ] Create a plan to regular patch security vulnerability
- [ ] Shutoff non used services, e.g., Webhook, Plug-In, API, etc.

**Comment by NickCorcoran** [comment]
Retiring Mautic service
