### ISSUE TITLE
Upgrade RocketChat from v3 to v4

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#2342]
**Describe the issue**
Current version of RocketChat is 3.18.7.  Upgrade to v4.x (latest stable release).

**Additional context**
Because this is a major upgrade, extra testing is required.
https://github.com/RocketChat/Rocket.Chat/releases

**Definition of done**
- [x] Release notes reviewed and significant changes are noted in "review changes" ticket
- [x] Upgrade is tested in Dev
- [x] Detailed upgrade plan is prepared for Prod, including possible rollback
- [x] Prod upgrade is scheduled and announced
- [x] Prod upgrade complete
