### ISSUE TITLE
 StackOverflow Proof of Value

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2380]
**Describe the issue**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [ ] connect our auth with KeyCloak
- [ ] StackOverflow team guides us through styling our instance with their OOTB editor
- [ ] add our privacy language for terms of use for our users as required in various options available to us
- [ ]  set up training for our team of teams through April to end of month
- [ ] adoption for the BCDevExchange Community
- [ ] manage the amount of people that sign up; not as to restrict, but a big red flag if it goes over 700 for this exercise
