### ISSUE TITLE
Certbot - for shared services ssl cert auto renewal

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2386]
**Describe the issue**
look into certbot to see how we can make use of it!

**Additional context**
Identify what will need to happen/be delivered for this to be completely done
- [ ] certbot istore request
- [x] test deployment of certbot
- [x] plan on installing certbot for all platform shared services
- [ ] discuss on platform support?

**Comment by ShellyXueHan** [comment]
@w8896699 also take a look at the new feature coming to openshift 4.10: https://cloud.redhat.com/blog/announcing-the-technology-preview-of-cert-manager-operator-for-red-hat-openshift-4.10 Might be helpful to decide on the use case for certbot!

**Comment by w8896699** [comment]
This cannot be integrated with the iStore request process; a manual iStore request must still be created for each certificate request before they will be approved.

**Comment by w8896699** [comment]
I have tried to install Certbot in registry dev environment, and tested that it can successfully install certification to the route from letsencrypt's ACME server. Waiting for confirmation from Justin Thomas for the correct URL for gov entrust server.

**Comment by w8896699** [comment]
We are not gonna recommend teams on our platform to use certbot yet, will wait a little bit longer until Justin's team get ready.
