### ISSUE TITLE
Openshift 201 training content development - MVP

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2446]
This Epic includes the work required to develop the content for the new OCP 201 training that will be delivered by the Platform Services Team.

Additional Context:
- The new training will have the delivery format similar to Openshift 101 - 1/2 day lecture,1 week later a 1/2 day Lab follow-up session and 1 week later 1/2 day Lab wrap up session.
- The training will be delivered by the same group that today delivers Openshift 101: Cailey, Shelly and Billy and plus Matt

DoD:

The following topics "must-have" topics have been delivered and signed off:
- [x] Resource management
- [x] App Resource Tuning
- [x] CI/CD pipeline automation with Openshift pipelines
- [x] Using Vertical Pod Autoscaling
- [x] Using Horizontal Pod Autoscaling
- [x] Configure apps for resiliency and HA
- [ ] PVC Backups
- [x] PodDisruptionBudgett
- [x] Post outage check up
- [x] Scaling the right way
- [x] Best practices for image management

**Comment by mitovskaol** [comment]
PVC backups are covered in OCP 101
