### ISSUE TITLE
SSO realm usage - prep for gold migration

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2454]
**Describe the issue**
SSO team has asked us to review our SSO realm usages and determine if we can merge some of the clients in to a common realm. This is the preparation for Keycloak migration to Gold. We want to make sure migrating between realms works for shared services first before we can tell if the SSO migration to Gold will work!

**Definition of done**
- [x] identify our services/clusters usage of SSO realms and the current usage, check if there are any custom setup/config
- [x] discuss on which ones would be migrated to a common SSO realm
- [x] discuss on which of our realms can be merged together to reduce the amount
- [x] reach out to each service lead and discuss about the migration effort
- [x] plan on the migration/merge

All updates tracked here:
https://docs.google.com/spreadsheets/d/1IB4MZyvE7fv6IPpmjq2a21CHUnvNF6kFWBELUPGgIek/edit#gid=0

All services list and connect with the service lead:
- [x] openshift clusters
- [x] artifactory - Cailey
- [x] vault - myself
- [x] sysdig - myself
- [x] rocketchat - myself and Monica
- [x] registry - Oamar
- [x] mautic - Billy
- [x] stackoverflow - Nick
- [x] argocd - Ian
- [x] private cloud doc - Tyler

**Comment by ShellyXueHan** [comment]
### Updates:
Realm migration progress to move all SSO usage to `kq56c126` realm:

- `Rocketchat` is currently waiting for all upgrade to be complete, then I’ll retire Reggie and switch the realm at the same time
- `Registry` is undergoing a rebuild, so SSO change will happen on the new app instead
- Waiting for solution/suggestion about what to do with `ArgoCD` group usage
- `Vault` and `sysdig` should be fine too according to the user creation pattern, will need to plan for time to do the actual SSO migration
- `Artifactory` is currently blocked as we are waiting for feedback from support on it’s user config
- `mautic` should be good to go, need to plan with service lead

**Comment by ShellyXueHan** [comment]
Prep work is completed!
