### ISSUE TITLE
Private Cloud site MVP Launch

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2534]
This Epic includes all activities required to build and launch the MVP version of the new Private Cloud website in WordPress.

DoD:
- [x] all content is developed and signed off by Olena
- [x]  Update the content to link to the existing tech docs in DevHub (the links will be updated to point to the new tech doc website once it is available)
- [x] all content is loaded into the TEST WP instance
- [x] Create site map.xml and robot.txt to make content searchable by Google
- [x] PROD WP instance is available 
- [x] Migrate content from TEST to PROD WP instance
- [x]  Assign cloud.gov.bc.ca/private-cloud/ to PROD WP instance

Notes:
Exclude from MVP (these items will be in the next phase of the site development):
 - custom menu 
 - Platform status indicator (Recommended as Priority #1 post-MVP)
 - Eventbrite Openshift training regitation page
 - Mautic integration with WP (Recommended as Priority #2 post-MVP)

**Comment by theresawuzhere** [comment]
@mitovskaol I read the DoD and I'm wondering why we want to use the "Beta" tag on the site? What is that meant to denote?

**Comment by mitovskaol** [comment]
`Beta` would allow us to launch the website without having all core functionality available on Day 1. e.g. search may not be working on Day 1. But if you think that all the features listed in the DoD cover the core functionality of the website , we do not need the Beta label.

**Comment by theresawuzhere** [comment]
@mitovskaol I'm hesitant to put "beta" on a website because people might think the content is beta and not official and final. I think search is pretty core, but not a MUST because a 50 page website shouldn't be that hard to browse. 

The things you have as "excluded from MVP" make sense, have workarounds, and the user wouldn't know that we intend to add these things. 

What do you think of this?

**Comment by mitovskaol** [comment]
@theresawuzhere yup, it makes sense, I've removed the Beta sticker from the DoD

**Comment by theresawuzhere** [comment]
List of things to do, from the content side: 

- [ ] Latest alert
- [ ]
- [ ]
- [ ]
- [ ]
