### ISSUE TITLE
OCP 4.9 SILVER Upgrade

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#2576]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.9.

CHG0037738 for hard prune and trident upgrade
CHG0037743 for OCP 4.9 upgrade

**Additional context**

**Definition of done**
- [x] Execute RFC for Registry Hard Prune.
- [x] Execute RFC for OCP upgrade and firmware updates.
- [x] SILVER upgraded to OCP 4.9.

**Comment by tbaker1313** [comment]
This is completed. Removed the ticket for the two masters that have NIC issues and will deal with that independently for now.
