### ISSUE TITLE
GitHub Enterprise Repo Migration

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2785]
Initially the wrong type of GitHub Enterprise was setup, so we got a new one put in place.
Repos need to be migrated.

- [x] Health Org repos
- [x] CITZ Org repos
- [x] Social Sector repos
- [x] Platform Services Org repos - create tickets for all

here are a number of repos in our existing GitHub Enterprise (https://github.com/bcgov-platform-services) that need to get moved to the new one (https://github.com/BC-Gov-PaaS-Platform-Services). Please let me know who is going to move so I can grant you access. We will not bother moving the Aqua ones as no longer relevant.
These are the repos:

https://github.com/bcgov-platform-services/acs-automation (Shelly)
https://github.com/bcgov-platform-services/platform-gitops-vault (Shelly)
https://github.com/bcgov-platform-services/benny-operator (Ian)
https://github.com/bcgov-platform-services/warden-operator (Ian)
https://github.com/bcgov-platform-services/github-sandbox (Ian)
https://github.com/bcgov-platform-services/platform-gitops-container (Ian)
https://github.com/bcgov-platform-services/platform-gitops-calgary-clab-namespaces (Ian)
https://github.com/bcgov-platform-services/platform-gitops-kamloops-klab-namespaces (Ian)
https://github.com/bcgov-platform-services/platform-gitops-kamloops-silver-namespaces (Ian)
https://github.com/bcgov-platform-services/platform-gitops-kamloops-gold-namespaces (Ian)
https://github.com/bcgov-platform-services/platform-gitops-calgary-golddr-namespaces (Ian)

**Comment by NickCorcoran** [comment]
Need to do a final check on migrated repos and then kill old organization.

**Comment by IanKWatts** [comment]
Hi @NickCorcoran looks like this epic is all done.  Should it be closed?

**Comment by NickCorcoran** [comment]
Yes, I'll close this.  DevX is now responsible for GitHub in general anyhow.  Thanks @IanKWatts
