### ISSUE TITLE
OCP 4.10 SILVER Upgrade

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#2889]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.10.

**Additional context**

**Definition of done**
- [x] Execute RFC CHG0040767 for Registry Hard Prune.
- [x] Execute RFC CHG0040768 for OCP upgrade and firmware updates.
- [x] SILVER upgraded to OCP 4.10.

**Comment by tbaker1313** [comment]
This is completed but will do a thorough QA to make sure everything is working as expected.

**Comment by tbaker1313** [comment]
Completed.
