### ISSUE TITLE
Resource Configuration for Platform Shared Services

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2910]
**Describe the issue**
Several platform services does not have proper resource configuration, and the namespace does not have quota or limit range.

**How does this benefit the users of our platform?**
Prevent huge resource usage.

**Definition of done**
- [ ] identify which services need to work on
- [ ] resource setting with Jason's guidance
- [ ] apply resource config via CCM
