### ISSUE TITLE
Video Walkthrough of Lab Exercises in OpenShift 201 

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2985]
**Describe the issue**
Create a video walkthrough of the OpenShift 201 lab exercises. 

**Additional context**
This was requested by a lab participant, and would assist people to attend the OpenShift 201 lab independently. 

This would require consideration of allocating additional training namespaces for independent learners. 

**How does this benefit the users of our platform?**

Support 201 learners, provides and asynchronous learning option for OpenShift 201. 

**Definition of done**

- [ ] Record video content
- [ ] Record narration
- [ ] Edit video content
- [ ] Publish video to youtube, add chapter markings
