### ISSUE TITLE
Video Walkthrough OpenShift 101 lab

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2986]
**Describe the issue**
Create a video walkthrough of the OpenShift 101 lab exercises. 

**Additional context**

**How does this benefit the users of our platform?**

Support 101 learners with completing the lab exercises

**Definition of done**

- [ ] Record video content
- [ ] Record narration
- [ ] Edit video content
- [ ] Publish video to youtube, add chapter markings

**Comment by mtspn** [comment]
Convert this ticket to an epic, with detailed tickets for each topic. Estimate approximately 3 per topic.
