### ISSUE TITLE
Uptime.com STRA - Recommendations

### ISSUE THREAD

**Issue by AvneetKahlon** [BCDevOps/developer-experience#3011]
**Describe the issue**
Some risks are assessed during STRA activity of Uptime.com SaaS product. The recommendations to fix these risks are stated below.

**Additional context**
Refer to Uptime.com STRA
**How does this benefit the users of our platform?**

**Definition of done**

- [x] Investigate subaccounts to appropriately segregate checks between separate teams

- [x] Enable 2FA for all accounts 

- [x] Investigate SSO Integration to Azure AD
