### ISSUE TITLE
Develop usability testing plan for PO persona

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3057]
**Describe the issue**
In order to do usability testing on the new Product Registry, the PO persona and use cases need to be properly defined. 

**Tasks**

- [x] Met with SMEs to get their input 

- [x] Create PO persona for testing

- [x] Create list of functionalities a PO would require of the registry for testing

- [x] Create use cases for testing

**How does this benefit the users of our platform?**
Usability testing ensures that Product Owners needs are met in terms of functionality and usability. 

**Definition of done**

- [x] Tasks are completed and usability testing is ready to commence

**Comment by alexandralloyd** [comment]
Interview script: https://docs.google.com/document/d/1e-TGw9SlSEetIShBlnTJRuEVjqw8jtYhFISbeBN5RMs/edit

**Comment by alexandralloyd** [comment]
Outcomes of interviews: https://app.mural.co/t/platformservices5977/m/platformservices5977/1664913951327/550b67c80ada0bba212fb1f26adfcea61d6c6d4e?sender=ubf58a7267c86aa8dcd571926

**Comment by alexandralloyd** [comment]
Personas: https://app.mural.co/t/platformservices5977/m/platformservices5977/1663715940927/490fe113c0d80ebf703e36f0a84963be3b1367ec?sender=ubf58a7267c86aa8dcd571926

**Comment by alexandralloyd** [comment]
Script: https://docs.google.com/spreadsheets/d/1UHzgaRnZf_NeF3FI9HoRjfnFACCMGOeLUJQgcjDEo2A/edit#gid=0
