### ISSUE TITLE
Develop usability testing plan for Read-Only Admin persona

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3063]
**Describe the issue**
In order to do usability testing on the new Product Registry, the Read-Only Admin persona and use cases need to be properly defined. 

**Tasks**

- [x] Met with SMEs to get their input 

- [x] Create PO persona for testing

- [ ] Create list of functionalities a Read-Only Admin would require of the registry for testing

- [ ] Create use cases for testing

**How does this benefit the users of our platform?**
Usability testing ensures that Read-Only Admin needs are met in terms of functionality and usability. 

**Definition of done**

- [ ] Tasks are completed and usability testing is ready to commence

**Comment by alexandralloyd** [comment]
Personas: https://app.mural.co/t/platformservices5977/m/platformservices5977/1663715940927/490fe113c0d80ebf703e36f0a84963be3b1367ec?sender=ubf58a7267c86aa8dcd571926

**Comment by alexandralloyd** [comment]
Script:
https://docs.google.com/spreadsheets/d/1UHzgaRnZf_NeF3FI9HoRjfnFACCMGOeLUJQgcjDEo2A/edit#gid=391095470
