### ISSUE TITLE
Business Analysis work for Product Registry

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3069]
**Describe the issue**
In order to conduct proper usability testing, a business process diagram outlining the current the internal processes that occur within the Product Registry should be created. This should be in the form of a swim-lane diagram that lists users, actions, and products the Registry interacts with and/or that interact with the registry.

**Additional context**
No such map currently exists, so building an accurate one from scratch will take time considering the complexity of the registry and all the other services it interacts with.

**Tasks**

- [x] Met with SMEs

- [x] Build preliminary model based on research

- [x] Get SMEs to confirm model

- [x] Make any changes that SMEs suggest

**How does this benefit the users of our platform?**
Allows for usability testing for the Registry.

**Definition of done**

- [x] All tasks are completed

**Comment by alexandralloyd** [comment]
Incorporated feedback from Billy, Ian, Olena and Oamar.
