### ISSUE TITLE
Book Interviews for Tech Docs Content Testing

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3071]
**Describe the issue**
Book 6 user interviews for testing the new [technical documents site](https://beta-docs.developer.gov.bc.ca/) for usability based on [this](https://docs.google.com/document/d/1FfBVNU9RvsylLo4OEkaX4oTsqouBAHb2p8ppz1YXeiU/edit) guide. 

**Additional context**
Need to run through the guide with a SME to see if any edits need to be made before the final testing. 

**Tasks**

- [ ] Run through a pilot interview with SME and make necessary edits to research guide

- [ ] Book 6 interviews for participants

- [ ] Get at least one SME to attend each interview

**How does this benefit the users of our platform?**
Ensure important important information on our site is findable and understandable for users. 

**Definition of done**

- [ ] All tasks are completed

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.
