### ISSUE TITLE
Develop usability testing plan for non-authorized users 

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3076]
**Describe the issue**
In order to do usability testing on the new Product Registry, the non-authorized persona and use cases need to be properly defined. 

**Tasks**

- [x] Met with SMEs to get their input 

- [x] Create non-authorized persona for testing

- [x] Create list of what a non-authorized user would see

- [x] Create use cases for testing

**How does this benefit the users of our platform?**
Ensure that non-authorized users aren't able to access sensitive information.

**Definition of done**

- [x] Tasks are completed and usability testing is ready to commence

**Comment by alexandralloyd** [comment]
Personas: https://app.mural.co/t/platformservices5977/m/platformservices5977/1663715940927/490fe113c0d80ebf703e36f0a84963be3b1367ec?sender=ubf58a7267c86aa8dcd571926

**Comment by alexandralloyd** [comment]
https://docs.google.com/spreadsheets/d/1UHzgaRnZf_NeF3FI9HoRjfnFACCMGOeLUJQgcjDEo2A/edit#gid=709654795
