### ISSUE TITLE
OpenShift STRA Update - OCP 4.10 and NSX-T implementation

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#3163]
It has been a while since the last STRA update was completed.  This review will include looking at services that have been added/removed to/from OpenShift over the past number of versions (major changes) and introduction to the NSX-T governed cluster implementation within the SDN Zone.

- [x] Review existing STRA
- [x] Update Based on changes up to v4.10
- [x] Info/doc gathering for SDN Zone and Emerald implementation
- [x] Document for STRA context
- [x] Identify risks
- [x] Identify mitigations
- [x] Review with SDN implementation team and adjust as necessary
- [x] Create SoAR
- [x] Review and Sign-off

Definition of Done:
- STRA complete and review/sign-off complete with product owner
