### ISSUE TITLE
Allow IDIR contacts collected in Platform Services Registry access resources in Emerald Cluster

### ISSUE THREAD

**Issue by ShovelHand** [BCDevOps/developer-experience#3298]
**Describe the issue**
With contact information for Product Owners and Technical Leads being switched from Git identities to IDIR, we need to make sure IDIR users can access secrets in vault and get their requests provisioned. 

**Additional context**
This is especially important for Emerald, which will not be using Git identities at all. 
Work will be relevant for both 1.0 and 2.0 versions of Platform Services Registry

**How does this benefit the users of our platform?**
They will be able to access secrets from Vault, stuff like Application IDs and Secrets. 

**Definition of done**
- [x] Users in Platform Services Registry can add by looking up IDIR users. 
- [x] Requests can be provisioned with these identities, though the user data is slightly different
- [x] TL's and Product owners with IDIR identities can access Vault secure details of products they are contacts on.
