### ISSUE TITLE
OCP 4.11 SILVER Upgrade

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3333]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.11.

**Additional context**

**Definition of done**
- [x] Execute RFC for Registry Prune.
- [x] Execute RFC for OCP upgrade and firmware updates.
- [x] SILVER upgraded to OCP 4.11.
