### ISSUE TITLE
OCP 4.10 EMERALD Upgrade

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3349]
**Describe the epic**
Epic to track all work upgrading EMERALD to OCP 4.10.

**CHANGES**

**Definition of done**
- [x] Execute RFC for OCP upgrade prep
- [x] Execute RFC for OCP upgrade
- [x] EMERALD upgraded to OCP 4.10.

**Comment by wmhutchison** [comment]
EPIC now fulfilled.
