### ISSUE TITLE
OCP 4.10 KLAB2 Upgrade

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3354]
**Describe the epic**
Epic to track all work upgrading KLAB2 to OCP 4.10.

**CHANGES**

**Definition of done**
- [x] Execute RFC for OCP upgrade prep
- [x] Execute RFC for OCP upgrade
- [x] KLAB2 upgraded to OCP 4.10.
