### ISSUE TITLE
Developer Experience Team - Knowledge and service transfer

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3483]
**Describe the issue**
We are going to transfer several services to the Developer Experience Team.

- [x] mobile platform
- [x] DevHub
- [x] Stackoverflow (mainly the admin tasks, Nick has transferred most to Karl already. Shea is working on the SSO migration bit)
- [x] Repo-Mountie (github app)
- [x] github orgs (bcgov, bcgov-c, enterprise org, BCDevOps)
- [x] dockerhub org (admin task)
- [x] NPM org (admin task)
- [x] devops requests (currently both Monica and Helen is taking care of this service)
- [x] uptime.com (Billy and Artem will take care of our instance, service shared on SaaS page too)
- [x] pcard: github, Apple and Google, Rocketchat, StackOverflow
- [x] Just-ask
- [x] rocketchat (wait for human resource)

**Definition of done**
- [x] service transition plan and timeline
- [x] complete dependencies and get the services into good status
- [x] KTs

### Questions:
- should Developer Experience Team use a different KeyCloak realm?
- is there a separate pCard?
- is DevHub still in use? namespace migration needed?

### Dependencies/Blockers
Rocketchat:
- upgrade (rollout on Feb 1st, but still troubleshooting upgrade issue. ETA Feb 10)
- SSO migration (will start after upgrade is settled, will take ~2 weeks)

Stackoverflow:
- SSO migration (currently testing. Once tested, migration will happen in one day)

**Comment by ShellyXueHan** [comment]
### Update:

Here are the action items after initial discussion:

- Phillips, Shea CITZ:EX share the spreadsheet of products to be transferred (reviewed by Karl and Olena)
- Han, Shelly CITZ:EX to shirt size the effort of the products discussed today so they can be prioritized as people become available
- Phillips, Shea CITZ:EX to set up the next meeting as people on the team become available

**Comment by sheaphillips** [comment]
@ShellyXueHan see below for the excerpt from the spreadsheet I mentioned. Feel free to move this into the body of the Epic (I don't seem to be able to edit). 

| Service/Tools Name                                                                   | Responsibilities                                                                                                                                                                                                                                                                                                                                   |
|--------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Apple Developer Program, iTunes & Google Play Store Access + Mobile Signing  Service | - manual managing of the signing process for BC Gov's mobile apps - managing corporate accounts for Apple Developer Program and product team access to  iTunes and Google play store   - user support, documentation for mobile app development best practices and guildelines for product teams  - apple mini set up in Kamloops Data Center      |
| Repo-Mountie                                                                         | - custom development, code maintenance and feature add-ons  - operations and maintenance (patches, upgrades, config changes, features enablement)  - user support, documentation                                                                                                                                                                   |
| Rocket.Chat & Reggie & Hubot (BCBot)                                                 | - operations and maintenance (patches, upgrades, config changes, features enablement) of Rocketapp in Gold  - user support, documentation                                                                                                                                                                                                          |
| StackOverFlow Configuration and Moderation                                           | - configuring the BC Gov's SaaS instance - managing the KeyCloak SSO integration - Moderation: fixing tag mistakes, reviewing Q&A for compliance with good writing practices  Notes: the support effort may grow as SOF adoption in BC Gov increases                                                                                               |
| DevHub (will be replaced by the new developer servicces inventory)                   | - custom development, code maintenance and feature add-ons   - operations and maintenance (patches, upgrades, config changes, features enablement)  - user support, documentation                                                                                                                                                                  |
| GitHub.com Org Administration                                                        | - SaaS service hosted by the vendor  - bcgov, BCDevOps and bcgov-c (private repos) GitHub organization management, feature enablement, billing and user membership management - devops-requests associated with user access to repos including private repo creation, installing GitHub apps into repos, etc - periodic clean up of inactive users |
| Just Ask!                                                                            | - custom developed app hosting in Silver cluster - operations and maintenance (patches, upgrades, config changes, features enablement)  - user support, documentation                                                                                                                                                                              |

**Comment by ShellyXueHan** [comment]
@sheaphillips I've sorted things into this list https://docs.google.com/spreadsheets/d/1qNhV1ZE0-ke1NoEgu2VgzJT0XXeGP48PSn3DcQTtW5o/edit#gid=0 with what they are and the effort to transition and maintain. The green ones are those that are low maintenance and ready to transition. Let me know whenever your team is ready, we'll count the task into our sprint ;)
