### ISSUE TITLE
RunWhen Evalutaion

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3498]
**Describe the issue**
This is to decide if RunWhen would be a tool/service that platform services team and product teams can use to implement the SRE model and automation troubleshooting.

**What is the Value/Impact?**
A new service for easy monitoring and troubleshooting

**What is the plan? How will this get completed?**
- RunWhen team create POC use case for the us to learn how it works
- evaluate if this is a good fit for us and product team

**Definition of done**
- [x] POC use cases ready for review
- [ ] research on compatible service that we already have and other products
- [ ] discuss on multi-tenant model
- [ ] RunWhen provide demo to the community for feedback and use case
- [ ] internal team discussion on whether we should proceed or not
- [ ] if yes, roadmapping and follow up

**Comment by mitovskaol** [comment]
The team has decided not to implement RunWhen at this moment, closing the EPIC.
