### ISSUE TITLE
Add Network Policies to namespaces

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#3543]
**Describe the issue**
The Compliance Operator has identified that several namepsaces do not have any Network Policy. Our default SDN does ensure no cross traffic between namespaces, but this should be reinforced with netpol.

**Additional Info**
```
diff --new-line-format="" --unchanged-line-format="" \
<(oc get  namespaces -o json |  jq -r '[.items[] | select((.metadata.name | startswith("openshift") | 
not) and (.metadata.name | startswith("kube-") | not) and .metadata.name != "default") | 
.metadata.name ]|.[]') \
<(oc get --all-namespaces networkpolicies -o json | jq -r '[.items[] | select((.metadata.namespace | 
startswith("openshift") | not) and (.metadata.namespace | startswith("kube-") | not) and 
.metadata.namespace != "default") | .metadata.namespace] | unique|.[]')
```

**Definition of done**
Add appropriate NetworkPolicy to following namespaces.

- [x] devops-archeobot (GOLDDR only )
- [x] devops-artifactory (GOLDDR and EMERALD only)
- [x] devops-artifactory-tools (All 4 PROD clusters)
- [x] devops-xray (GOLD, GOLDDR and EMERALD only)
- [x] edb-operator (EMERALD only)
- [x] kyverno (All 4 PROD clusters)
- [x] must-gather-operator (All 4 PROD clusters)
- [x] nsx-system (EMERALD)
- [x] nsx-system-operator (EMERALD)

**Comment by tmorik** [comment]
Four more namespaces have been found by the compliance-operator's scan. Tickets created and added to this EPIC. @AvneetKahlon, @NickCorcoran, if you are aware of these namespaces, could you please assign the appropriate person?
