### ISSUE TITLE
Vault Upgrade

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3549]
**Describe the issue**
We are receiving security report about Vault sidecar container from ACS. As the sidecar container is tide to the version of Vault Server, we should consider an upgrade with security patches asap.

**Definition of done**
- [x] come up with a upgrade path (as we potentially need to upgrade with each individual minor version)
- [x] Vault server upgrade
- [x] Vault injector upgrade
- [ ] hack script and dockerfile upgrade (will be reviewed during setup of lab vault)
- [x] terraform upgrade
- [ ] address issues found during upgrade activities
- [ ] explore autopilot for future upgrade (for lab only)
