### ISSUE TITLE
Helen -Onbarod checklist

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#3627]
ACCESS:
- [x] #3655
- [x] IDIR access and outlook setup
- [ ] Platform Services Vault namespace

Tools:
- [x] Install OC
- [x] Intsll ansible-playbook(easy install with brew)

Study:
- [x] Yaml
- [x] Jinj2
- [x] Kustomize
- [x] Ansible(ansible playbook). 
- [x] Helm
- [x] ocp101 and lab session

Plan to complete the above Study within two weeks

practice:
- [ ] deploy simple application
- [ ] make a kustomize version of that deployment
- [ ] make a ansible/jinja2 version of that deployment
- [ ] maybe? try to make a ci/cd pipline

Plan to complete the above practices within two weeks

**Comment by blueQcloud** [comment]
Google Doc of the notes I've made, will update with list of good resources. https://docs.google.com/document/d/1TdJj_NhIzbOdbF9qqxOtwGF0lPJeymzFMSgR6v1xQhU/edit?usp=sharing
