### ISSUE TITLE
OCP 4.12 SILVER Upgrade

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3746]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.12.

**Additional context**
RFC for SILVER upgrade May 28th - June 9th CHG0048445 & CHG0048444

**Definition of done**
- [x] Execute RFC for Registry Prune.
- [x] Execute RFC for OCP upgrade and firmware updates.
- [x] SILVER upgraded to OCP 4.12.
