### ISSUE TITLE
API Compatibility Issues between Openshift 4.11 and 4.12

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3775]
**Describe the issue**
After we upgrade to Openshift 4.12, AlertManager will start giving the Platform Operations team notifications regarding Kubernetes resources that need its API definition to be updated before an upgrade to Openshift 4.12 can be tendered. This EPIC will track efforts spent towards each cluster as we investigate and either deal with such compatibility issues ourselves internally if managed by us, or otherwise notifying stakeholders to do the same.

**Additional context**
https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-removed-features
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
https://access.redhat.com/articles/6955381

**All cluster audit results**
KLAB
Auditing cronjobs.v1beta1.batch
VERBS USERNAME USERAGENT
list patch watch system:serviceaccount:openshift-bcgov-crunchy:pgo postgres-operator/v0.0.0

GOLD
Auditing cronjobs.v1beta1.batch
VERBS USERNAME USERAGENT
get update system:serviceaccount:b8840c-tools:pipeline HashiCorp/1.0

GOLDDR
Nothing noted.

SILVER
Auditing cronjobs.v1beta1.batch
VERBS USERNAME USERAGENT
get system:serviceaccount:26e83e-tools:jenkins-1945 oc/4.10.0

Auditing horizontalpodautoscalers.v2beta1.autoscaling
VERBS USERNAME USERAGENT
get patch system:serviceaccount:af9df1-tools:pipeline Helm/3.11.3

**Definition of done**
- [x] All clusters that have been upgraded to OCP 4.11 have received evaluations for matching API calls needing remediation
- [ ] All remediation efforts that are internal (Platform Ops and Services teams) are completed.
- [ ] All remediation efforts requiring developer intervention has confirmed to be finished.
- [ ] Final confirmation that all clusters are agreed upon to be in an upgradable state to OCP 4.12
