### ISSUE TITLE
OCP 4.10 testing in KLAB2

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3866]
**Describe the epic**
Epic to track all work involved in upgrading KLAB2 to OCP 4.10-latest, testing all the components, and documenting the process in case anything needs to be updated or changed.

**Additional context**
* No Trident ticket since we've not updated to use a newer Trident. Do not see the need to attempt an upgrade of Trident for a maintenance upgrade of OCP.
* No Hard Prune ticket since we need to find out whatever's unblocked us doing this for our OCP 4.12 upgrade is still applicable here or not. Until known, erring on the side of caution and skipping this step.

**Definition of done**
- [x] KLAB2 upgraded to OCP 4.10.59
- [x] All Platform Ops features and components tested.
- [x] Upgrade and CHG documentation updated with new/changed steps as needed.
