### ISSUE TITLE
Christopher Onboarding

### ISSUE THREAD

**Issue by blueQcloud** [BCDevOps/developer-experience#3917]
ACCESS:
- [x] IDIR access and outlook setup
- [ ] Platform Services Vault namespace

Tools:
- [x] Install OC command line
- [x] Go through work station setup ticket and install dependencies

Study (in order of importance):
- [x] Yaml syntax
- [x] ocp101 and lab session
- [x] Kustomize
- [x] Helm
- [x] Ansible(ansible playbook)
- [x] Jinja2 templates
- [x] ocp201 and lab session

Practice (alongside readings):
- [x] create notes to refer back to for above topics
- [x] deploy simple full stack application with a database in open shift
- [x] create a deployment template for the application(important! )
- [ ] make a kustomize version of the deployment template
- [ ] make a ansible/jinja2 version of the deployment template
- [x] make a ci/cd pipline
