### ISSUE TITLE
Christopher Tan Co-op Road map

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#3927]
# Onboarding:

- [x] 1. Get to know the team, the platform, and the tools we use.
- [x] 2. Setup workstation and get access to the necessary repo(while waiting for idir)
- [x] 3. Learning the basic of the Openshift container platform.
- [x] 4. Build a simple docker image and push/deploy on localhost

# Training

- [x] 1. Openshift 101.
- [x] 2. Use the web console, the CLI
- [x] 3. Get experience of the full life cycle of an application on Openshift, from creating/deploying image to scaling, updating and deleting it. 
- [ ] 4. Learn some popular templating tools(tbd)?
- [x] 5. Openshift 201 training

# Project works

- [x] 1. Learn from comunity support
- [x] 2. Learn shared-services/tools that we have on the platform
- [x] 3. Choose a project/app to support and start taking some small tasks(follow the instructions and expections, one of the platform admin will help to review regularly)
- [x] 4. Co-op report

# Continuous Learning
For example: CI/CD pipline, cloud-native development. Encourage to explore any topics related to Openshift or DevOps in general, or even app development.
