### ISSUE TITLE
Community Meetup/Communications Improvements

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#4042]
**Describe the issue:** 
Current Community Meetup meeting series is difficult to manage and seems 'broken'. When one adds a new member or want to remove a participant from the list of invitees, the meeting invitation is sent to everyone on the list instead of changed only. That creates multiple spamming for the whole group. 

**Updates/Mailing Lists**
- Some people aren't getting updates
- Others are getting too many updates and want to be removed
- Ideally people should be able to self serve - sign up for the meetup series or remove them selves on demand

**Definition of done:** 

- [x] investigate a few options to resolve this issue: using a distribution list, using summer.gov.bc for scheduling, ask other teams how they manage a large group of meeting participants. 
- [x] update the list of participants removing people that don't want to be invited to the Community Meetup and adding those who have subscribed through Mautic 
- [x] possibly end the current series and create a new one with the updated list of participants
