### ISSUE TITLE
API Compatibility Issues between Openshift 4.12 and 4.13

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#4049]
**Describe the issue**
After we upgrade to Openshift 4.13 AlertManager will start giving the Platform Operations team notifications regarding Kubernetes resources that need its API definition to be updated before an upgrade to Openshift 4.13 can be tendered. This EPIC will track efforts spent towards each cluster as we investigate and either deal with such compatibility issues ourselves internally if managed by us, or otherwise notifying stakeholders to do the same.

**Additional context**
https://docs.openshift.com/container-platform/4.13/release_notes/ocp-4-13-release-notes.html#ocp-4-13-removed-features
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26

**All cluster audit results**
KLAB

GOLD

GOLDDR

SILVER

**Definition of done**
- [ ] All clusters that have been upgraded to OCP 4.12 have received evaluations for matching API calls needing remediation
- [ ] All remediation efforts that are internal (Platform Ops and Services teams) are completed.
- [ ] All remediation efforts requiring developer intervention has confirmed to be finished.
- [ ] Final confirmation that all clusters are agreed upon to be in an upgradable state to OCP 4.13

**Comment by tbaker1313** [comment]
More info about this process is found at https://docs.openshift.com/container-platform/4.13/updating/updating-cluster-prepare.html#updating-cluster-prepare
