### ISSUE TITLE
SDN - Review final technical dependencies are available before building out a suitable EPIC nest for upgrading KLAB2/EMERALD to OCP 4.12

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4158]
**Describe the issue**
Based on current knowledge, the last technical blocker is about to be lifted in the form of providing a compatible version of ncp that will support OCP 4.12. Once that is confirmed formally, we can start the planning out of of the nested EPICs specific to addressing this upgrade. 

We are looking for official release by VMware ncp version 4.1.1 or newer. ncp v4.1.0 was the previous official release, but didn't offer support yet for OCP 4.12.

**Additional context**
Will make use of current automation for ticket creation, but take notes in case we want to create a separate stack of tickets specific for handling the upgrades of these NSX-backed Openshift clusters going forward. This will be the first time we have attempted to upgrade our Openshift clusters based on an EUS cadence.

**How does this benefit the users of our platform?**
This ensures we can continue the timely upgrade of all of our Openshift clusters to continue receiving supported security patches. The last available security updates for OCP 4.10 will drop in September 2023, and after that, we need to upgrade to a newer version of Openshift to continue receiving updates.

**Definition of done**
- [x] Confirm official availability of new ncp release by seeing official Release notes in VMware documentation
~~- [ ] Work with Dan Deane regarding downloading new ncp and uploading to the Dockerhub account.~~
~~- [ ] Work through release notes and identify/remediate technical changes supporting ncp if required.~~

**Comment by wmhutchison** [comment]
Official release of ncp 4.1.1.1 is on or after August 15th. Will. re-check at that time to confirm official specs and compatibility. 

If it pans out, then we'll be scheduling two distinct upgrade waves that are being separated out since the new ncp is still compatible with OCP 4.10.

- [ ] Upgrade ncp to required version. Suitable windows of bake-in time is essential for this due to the essential nature of ncp. Also KLAB2 and EMERALD neither receive as much activity as regular Openshift clusters.
- [ ] Create a suitable nested EPIC for the upgrade of KLAB2/EMERALD to OCP 4.12 via EUS methods. A key part of this will be reviewing the the 4.11 and 4.12 upgrade runs for regular Openshift, and start by back-porting identified issues for note during this wave.

**Comment by wmhutchison** [comment]
Closing off this ticket, since we have confirmed ncp release exists. Another ticket will track the follow-up work involved with downloading new ncp.
