### ISSUE TITLE
SDN - OCP 4.12 Testing in KLAB2

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4244]
**Describe the epic**
Epic to track all work involved in upgrading KLAB2 from OCP 4.10 to 4.12, testing all the components, and documenting the process.

**Additional context**
Specific instructions for doing an EUS upgrade from OCP 4.10 to 4.12. Will need to ensure this gets adopted into the RFC Methodology for EMERALD. <https://docs.openshift.com/container-platform/4.10/updating/preparing-eus-eus-upgrade.html>

**Definition of done**
- [x] KLAB2 upgraded to OCP 4.12
- [x] All Platform Ops features and components tested.
- [x] Upgrade and CHG documentation updated with new/changed steps as needed.
