### ISSUE TITLE
SDN - API Compatibility Issues between Openshift 4.10 and 4.12

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4265]
SDN - API Compatibility Issues between Openshift 4.10 and 4.12

**Describe the issue**
After we upgrade to Openshift 4.12, AlertManager will start giving the Platform Operations team notifications regarding Kubernetes resources that need its API definition to be updated before an upgrade to Openshift 4.12 can be tendered. This EPIC will track efforts spent towards each cluster as we investigate and either deal with such compatibility issues ourselves internally if managed by us, or otherwise notifying stakeholders to do the same.

**Additional context**
https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-removed-features
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
https://access.redhat.com/articles/6955381

This EPIC and subsequent tickets underneath will benefit greatly from similar tickets created and processed for regular Openshift upgrades From Openshift 4.11 to 4.12, since there are no API deprecation items to note when upgrading from Openshift 4.10 to 4.11.

**All cluster audit results**
KLAB2
- TBD

EMERALD
- TBD

**Definition of done**
- [x] All clusters that have been upgraded to OCP 4.12 have received evaluations for matching API calls needing remediation
- [x] All remediation efforts that are internal (Platform Ops and Services teams) are completed.
- [x] All remediation efforts requiring developer intervention has confirmed to be finished.
- [x] Final confirmation that all clusters are agreed upon to be in an upgradable state to OCP 4.12

**Comment by wmhutchison** [comment]
Closing EPIC, EMERALD gets upgrades next week.
