### ISSUE TITLE
OCP 4.13 API Compatibility Issues Epic

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4438]
**Describe the issue**
AlertManager will start giving the Platform Operations team notifications regarding Kubernetes resources that need its API definition to be updated before an upgrade to Openshift 4.13 can be tendered. This EPIC will track efforts spent towards each cluster as we investigate and either deal with such compatibility issues ourselves internally if managed by us, or otherwise notifying stakeholders to do the same.

**Additional context**
Link to Release Notes removed features
https://kubernetes.io/docs/reference/using-api/deprecation-guide/

**All cluster audit results**
KLAB

GOLD

GOLDDR

SILVER

**Definition of done**
- [x] All clusters have received evaluations for matching API calls needing remediation
- [x] All remediation efforts that are internal (Platform Ops and Services teams) are completed.
- [x] All remediation efforts requiring developer intervention has confirmed to be finished.
- [x] Final confirmation that all clusters are agreed upon to be in an upgradable state to OCP 4.13

**Comment by tbaker1313** [comment]
Completed. Not required.
