### ISSUE TITLE
OCP 4.13 SILVER Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4464]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.13.

**Additional context**
CHG for SILVER 

**Definition of done**
- [x] Execute CHG for Registry Prune
- [x] Execute CHG for OCP upgrade and firmware updates
- [x] SILVER upgraded to OCP 4.13

**Comment by tbaker1313** [comment]
This is essentially completed, we are just waiting to resize the vms so leaving this open for now.

**Comment by tbaker1313** [comment]
Completed.
