### ISSUE TITLE
OCP 4.13 GOLD Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4468]
**Describe the epic**
Epic to track all work upgrading GOLD to OCP 4.13.

**CHANGES**
CHG for GOLD

**Definition of done**
- [x] Execute CHG for OCP upgrade prep
- [x] Execute CHG for OCP upgrade
- [x] GOLD upgraded to OCP 4.13

**Comment by tbaker1313** [comment]
Completed.
