### ISSUE TITLE
2024 Q1 - OCP 4.12 Testing in KLAB2

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4497]
**Describe the epic**
Epic to track all work involved in upgrading KLAB2 to the latest minor available version of Openshift 4.12, testing all the components, and documenting the process.

**Definition of done**
- [x] KLAB2 upgraded to OCP 4.12-latest.
- [x] All Platform Ops features and components tested.
- [x] Upgrade and CHG documentation updated with new/changed steps as needed.

**Comment by wmhutchison** [comment]
All done with this EPIC.
