### ISSUE TITLE
2024 Q1 - OCP 4.12 Upgrade in EMERALD

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4519]
**Describe the epic**
Epic to track all work upgrading EMERALD to match the OCP version on KLAB2 (4.12.44).

**Additional context**
CHG for EMERALD

**Definition of done**
- [x] Execute CHG for OCP Upgrade Prep for EMERALD.
- [x] Execute CHG for OCP upgrade and virtual firmware updates if applicable. Also including work with increasing APP VM disk.
- [x] EMERALD upgraded to OCP 4.12.44

**Comment by wmhutchison** [comment]
Closing EPIC as complete.
