### ISSUE TITLE
Vault - rebuild lab vault instance

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4614]
**Describe the issue**
We have lost the recovery keys from lab vault service, it's the best to recreate the instance and migrate existing secrets over.

**Definition of done**
- [x] plan for the migration
- [x] look up workloads using vault in lab clusters (klab, clab, klab2)
- [x] spin up new vault cluster
- [x] run through the instance/DR configuration and terraform setup
- [x] migrate secret
- [x] testing
- [x] decommission the old instance
