### ISSUE TITLE
OCP NSX 4.14 Testing in KLAB2 Epic

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4821]
**Describe the epic**
Epic to track all work involved in upgrading KLAB2 to OCP 4.14, testing all the components, and documenting the process.

**Additional context**

**Definition of done**
- [x] KLAB2 upgraded to OCP 4.14
- [x] All Platform Ops features and components tested
- [x] Upgrade and CHG documentation updated with new/changed steps as needed
