### ISSUE TITLE
OCP NSX 4.14 EMERALD Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4837]
**Describe the epic**
Epic to track all work upgrading EMERALD to OCP 4.14.

**Additional context**
CHG for EMERALD 

**Definition of done**
- [x] Execute CHG for Registry Prune
- [x] Execute CHG for OCP upgrade and firmware updates
- [x] EMERALD upgraded to OCP 4.14
