### ISSUE TITLE
User defined monitoring (update tech doc)

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4863]
@vivekratan88 is primary

**Tasks**
Update this page: https://docs.developer.gov.bc.ca/user-defined-monitoring/ 

**Section:** 
Add: Monitor user-defined projects using Alertmanager
Page is out of date and needs to be expanded now that Alertmanager is working

--- 

- [x] Review current content (valid, up to date?) 
- [x] Rewrite content 
- [ ] Send to Pilar for review (if possible at least 2 days before sprint review date - coordinate work) 
- [x] Send for additional peer review 
- [ ] Publish and create new build

**Comment by Pilargit12** [comment]
Hi @vivekratan88 @ShellyXueHan @StevenBarre  when creating the PR for the update of this document, please give me at least 4 days before sprint review to check this documentation as opposed to 2 days before sprint review - thank you so much!

**Comment by StevenBarre** [comment]
Looks like we should also document the need for a netpol to get ServiceMonitors working https://chat.developer.gov.bc.ca/channel/devops-registry?msg=JvkSubcpNFy2EtoDH

**Comment by vivekratan88** [comment]
Working on adding Netpol to ensure service monitors scrape required data

**Comment by StevenBarre** [comment]
https://github.com/bcgov/platform-developer-docs/pull/270

**Comment by Pilargit12** [comment]
@StevenBarre @vivekratan88 @ShellyXueHan  can you please tell me when my review is needed after SME's have provided their input and corrected these in the PR ? Thank you

**Comment by vivekratan88** [comment]
review changes done and sent for feedback, but netpol section has to be included and this needs to be tested. I have made service monitor in my cause using counter metric to send request counts and see if that is registered then later on have to apply netpol to see if that works.

**Comment by vivekratan88** [comment]
will have to check on the buildconfig file upon running it says forbidden could be permission issue, checking on this.

**Comment by vivekratan88** [comment]
completed reviews and merged.
