### ISSUE TITLE
OCP 4.14 SILVER Upgrade Epic

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5044]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.14.

**Additional context**
CHG for SILVER 

**Definition of done**
- [x] Execute CHG for Registry Prune
- [x] Execute CHG for OCP upgrade and firmware updates
- [x] SILVER upgraded to OCP 4.14

**Comment by wmhutchison** [comment]
Closing Epic. All associated tickets now complete.
