### ISSUE TITLE
OCP 4.14 GOLD Upgrade Epic

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5048]
**Describe the epic**
Epic to track all work upgrading GOLD to OCP 4.14.

**CHANGES**
CHG for GOLD

**Definition of done**
- [x] Execute CHG for OCP upgrade prep
- [x] Execute CHG for OCP upgrade
- [x] GOLD upgraded to OCP 4.14

**Comment by wmhutchison** [comment]
All tickets complete for this upgrade.
