### ISSUE TITLE
Copy of User defined monitoring (update tech doc)

### ISSUE THREAD

**Issue by vivekratan88** [BCDevOps/developer-experience#5079]
@vivekratan88 is primary

**Tasks**
Update this page: https://docs.developer.gov.bc.ca/user-defined-monitoring/ 

**Section:** 
Add: Monitor user-defined projects using Alertmanager
Page is out of date and needs to be expanded now that Alertmanager is working

--- 

- [ ] Review current content (valid, up to date?) 
- [ ] Rewrite content 
- [ ] Send to Pilar for review (if possible at least 2 days before sprint review date - coordinate work) 
- [ ] Send for additional peer review 
- [ ] Publish and create new build

**Comment by vivekratan88** [comment]
duplicate ticket
