### ISSUE TITLE
JIRA review ticket User defined monitoring (update tech doc) - Pilar review

### ISSUE THREAD

**Issue by vivekratan88** [BCDevOps/developer-experience#5123]
@vivekratan88 is primary

This JIRA ticket as per new process for Pilar to review since this a new section is added to the page.
Please reach out to Vivek Ratan for more details, if required. This related to #4863 ticket

**Tasks**
Update this page: https://docs.developer.gov.bc.ca/user-defined-monitoring/ 

**Section:** 
Add: Monitor user-defined projects using Alertmanager
Page is out of date and needs to be expanded now that Alertmanager is working

--- 

- [x] Review current content (valid, up to date?) 
- [x] Rewrite content 
- [x] Send to Pilar for review (if possible at least 2 days before sprint review date - coordinate work) 
- [x] Send for additional peer review
