### ISSUE TITLE
OCP NSX 4.14 EMERALD Upgrade Epic

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5193]
**Describe the epic**
Epic to track all work upgrading EMERALD to OCP 4.14.

**Additional context**
CHG for EMERALD 

**Definition of done**
- [ ] Execute CHG for Registry Prune
- [ ] Execute CHG for OCP upgrade and firmware updates
- [ ] EMERALD upgraded to OCP 4.14
