### ISSUE TITLE
Develop a plan for allowing projects to exceed quota

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#5216]
**Describe the issue**
Some projects experience brief, large spikes in traffic and need a way to automatically and quickly adapt to the high volume of traffic that would otherwise exceed their baseline quota.  Come up with a plan to address this that makes sense from both a business standpoint and a technical one.

**What is the Value/Impact?**
Provide a level of service that these projects would otherwise have to go to a public cloud platform for.

**What is the plan? How will this get completed?**
* Hold meetings with multiple project teams that would be candidates for this kind of service.
* Hold meetings with the Platform Services team to discuss details and concerns.
* Prepare a definition of the service to inform development of the operator and related resources.

**Identify any dependencies**
* User feedback
* Team consensus

**Definition of done**
- [x] A proof-of-concept has been demonstrated
- [x] Consultations have been held with project teams
- [x] Discussion among the Platform Services team has resulted in a service definition

**Comment by IanKWatts** [comment]
The service definition is in this issue:
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5291

A separate epic will be created for the various tasks associated with preparing the service for beta testing by users.
