### ISSUE TITLE
Chatbot - going production

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#5315]
**Describe the issue**
The POC for the GenAI chatbot project is completed:
- We have compared the following AI services, and chosen Azure OpenAI to be the best in performance and effective in cost:
  - GCP Vertex AI
  - AWS Bedrock
  - Azure OpenAI
- A custom ChatApp has been built and deployed in Silver cluster that integrates into Rocket.Chat

Next step is to move the project into production environment.

**Definition of done**
- [ ] collect statistics on Rocky's history for performance overall
- [ ] cost analysis
- [ ] STRA and PIA
- [ ] move project from Forge to Live
- [ ] create automation for knowledge base updates
- [ ] build chatApp CD pipeline
- [ ] create maintenance plan
- [ ] knowledge sharing
