### ISSUE TITLE
OCP 4.14 SILVER Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5421]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.14.

**Additional context**
CHG for SILVER 

**Definition of done**
- [ ] ~Execute CHG for Registry Prune~
- [x] Execute CHG for OCP upgrade and firmware updates
- [x] SILVER upgraded to OCP 4.14

**Comment by tbaker1313** [comment]
Completed.
