### ISSUE TITLE
Verifiable Credential - further down the road - part 2

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#566]
### Tasks:
- [ ] 1- test out how to provide VC as an identity provider to BCGov app teams
- [ ] 2- explore on operational plans for issuers and verifiers for BCGov
- [ ] 3- create demo video for community distribution

### Details:
Step 1:
- Test out if a master VC realm (same approach as IDIR and GitHub) works
- If so, how should provisioning process be automated
- and how can app teams update their config for issuer and credential attributes work
- if not, figure out other ways

**Comment by ShellyXueHan** [comment]
Not relavant.
