### ISSUE TITLE
SSO Test Upgrade Retrospective

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#587]
## A lot of things went wrong

- temporary keycloak deployment config manifest was missing the correct image stream for keycloak 7.4-78. There is a note of in the install steps but it was easily missed. 
> we should make it VERY CLEAR you need modify the image reference in that deployment config (dc.spec.template.spec.containers[0].image)

- the jenkins job expired. This means we could not run the job as it would trigger a recreate deployment of the dev sso instance (this would clear any user sessions for people who were testing in keycloak-dev). We had to run the jenkins step for deploy test manually)

- the deploy test step utilized the bcdk `npm run deploy -- --pr=<pr> --env=test` 
  - this step would have triggered a redeployment of the patroni statefulset alongside the keycloak upgrade (this would likely cause db corruption). This is unavoidable because the bcdk magically applies labels to the stateful set (env-id=<num>).
  - the bcdk overwrote the db secret (created a new user/pw). We needed restore that with a backup template we thankfully had. 

## My thoughts

by far the most painful thing was bcdk's magic. We should stop using bcdk and be much more explicit on how we manage the infrastructure code. all magical labels that are added can be annotated in the infra code itself. 

## TODO:
- [x] the test local user needs a role!
- [x] put obvious note in the temporary sso upgrade job to change the istag referrence
- [x] add steps to manually trigger deployment based on bcdk settings
- [x] update instructions that has hard coded db values
- [x] work on scripts to drop trasactional tables from db

**Comment by patricksimonian** [comment]
also db name was inconsistent between dev and test (so we just need update instructions for that)

**Comment by patricksimonian** [comment]
dropping all the transaction tables during the schema migration is manual and painful (error prone). I had to  list tables `/d` and copy and paste all the transaction tables and craft a `DROP TABLE` expression. It sounds like we might be able to craft a SQL query to select and drop all txn tables. 

`SELECT name FROM blah WHERE name = 'xxx*xxx'` and then pipe that into the DROP table exression

**Comment by adodge-bcg** [comment]
Less a thing that went wrong and more a thing to remember, but the output from 'npm run deploy -- --pr=<pr> --env=test' was a list and needed to be wrapped in (list?) order to then apply the dc.

**Comment by ShellyXueHan** [comment]
@adodge-bcg yea good point! Comments added for next time: https://github.com/BCDevOps/developer-experience/pull/575/files#diff-f7ee672c788868b2f996aa39d6513848R69-R83
