### ISSUE TITLE
Realm-o-Matic updates

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#622]
### Background:
this is to get prep for migrating realm-o-matic to OCP4

### Tasks:
- [x] update sso integration
- [x] update sso refs
- [x] update doc
- [x] update service url to developer
