### ISSUE TITLE
NRM Aporeto Enforcer configuration (OCP 4 <> Zone B)

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#658]
**Describe the issue**
Setup Aproeto enforcer proxies for NRM OCP 4 <> Zone B connectivity

**Which Sprint Priority is this issue related to?**
Early adopters

**Additional info
Documize - Aporeto enforcer setup guide
https://docs.pathfinder.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-platform-services/d/bonkqskhpp5rkld1o310/aporeto-enforcer-in-network-zone-setup-guide

**Definition of done**
- [ ]  NRM - Open up firewall b/w OCP 4 and existing Aporeto enforcer proxies in Zone B (LK to get details)
         - This will allow the DevOps team to re-start their work on configuration, take some performance benchmarks to compare in new location
- [ ] Lab/NRM - ensure correct access to Aporeto console to view/edit proxy policies
- [ ]  Lab/DXC - update playbook for enforcer proxy creation for OCP 4
- [ ]  NRM - Create/identify DMZ subnet for new Aporeto proxies
- [ ]  NRM - iStore two RHEL8 VMs in DMZ subnet
- [ ]  Lab/DXC - once subnet identified, build enforcer proxies in that subnet
- [ ]  Lab - ensure correct access to create/edit proxy rules
- [ ]  NRM - configure new Aporeto proxies w/ rules from old
- [ ]  NRM - open firewall rules b/w Aporeto proxy subnet and Zone B subnet
- [ ]  NRM - test and benchmark - compare w/ previous benchmarks taken
- [ ]  NRM - request tear-down of Zone B proxies
- [ ]  NRM - close firewall rule b/w OCP 4 and Zone B subnet

**Comment by NickCorcoran** [comment]
Firewall rule to Zone B to be implemented on 12 Nov.

**Comment by sbarre-esit** [comment]
Punting to @wmhutchison as he holds SCTASK0097323 which tracks the billable time for this task.

**Comment by NickCorcoran** [comment]
Abandoned due to switch in SDN focus.
