### ISSUE TITLE
Develop an approach to monitoring OCP 4 Platform Essential Services

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#670]
**Describe the issue**
As a Platform Services Team member I need to develop reliability metrics for the Openshift Platform and the Shared Services on it . These metrics will track availability and performance of essential Platform and Shared Service. 
It is anticipated that 3 workshops will be required to identify the essential service, ther realiability metrics for them and the technoogy stack to monitor the metrics and capture the historic data in a dashboard.

**Additional context**
A service are considered essential **from the application operations perspective** if **any disruption to the operations of the service results in a disruption to the operations of an application production workload** running on the Platform.

**Definition of done**
 - [x] Prepare for the Workshop #1 where the Platform Services Team will use the KeyCloak SSO app as a sample app to understand what services the app production operations depends on on the Platform. The outcome would be a skeleton diagram outlining the essential services that the KeyCloak app relies upon i.e. Openshift routing service, Openshift API service, Docker service, Trident Storage Service, etc. It is recommended to create the diagram in a Miro board. 
- [x] Run the Workshop #1 with the Platform Service Team to fill in the gaps and add more detail to the essential .
- [x] Run the Workshop #2 with the developer leads from the Community to review and expand the list of the essential services. 
- [x] Run the Workshop #3 with the PS Team, Platform Operations Team and RedHat experts to discuss how the essential services can be monitored and how alerting can be enabled for them.

**Comment by sbarre-esit** [comment]
OpenShift Online (v3) has a bunch of code published for how they monitor with Zabbix. There are some useful cron jobs in https://github.com/openshift/openshift-tools/tree/prod/scripts/monitoring that might give some hints on things to monitor.

**Comment by mitovskaol** [comment]
Thanks for the info @sbarre-esit  First we need to figure out what services are indeed essentail for production workloads on the Platform because you and I will get pages when any of these services goes down, so need to be smart and selective about what we call an "essential" service :)

**Comment by mitovskaol** [comment]
The MVP described in this ticket has been implemented as a new Reliability Dashboard for the Platform and its essential services at [http://status.developer.gov.bc.ca/](http://status.developer.gov.bc.ca/)

All future enhacements will be tracked in separate tickets.
