### ISSUE TITLE
SG - Upgrade KLAB and CLAB to OCP4.6

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#674]
**Describe the issue**
OpenShift 4.6 has been released. We need to estimate all the parts of the upgrade and work to test and document all the steps.

**Additional context**
This [EPIC](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/431) tracks all the tickets in case this ends up spanning multiple sprints.

**Definition of done**
- [x] LAB upgraded to 4.6
- [x] PRs for all the components that need to be changed
- [x] Document the steps and order for the upgrade
