### ISSUE TITLE
SG - KeyCloak SSO Stabilization Effort

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#681]
An ongoing effort to improve the Keycloak SSO service performance and reliability. This sprint goal will focus on items:

- [x] start review session with Redhat experts
- [x] baseline metric collection for KeyCloak (user login flow)
- [ ] historic monitoring with Sysdig/Prometheus 
- [ ] optimize resource allocation and deployment setting for KeyCloak service production instance

Value Add: ideally have a more reliable SSO service, and a faster time to detect
