### ISSUE TITLE
SG - Early Majority APP Migration Preparation

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#682]
As we are approaching the Early Majority App Migration Kick-off on Dec 2, we need to prepare a worhsop for Platform Teams (will be run in Dec) that outlines the key points about the app migration to the Silver cluster and points them to the relevant self-help docs.

Definition of Done:
 - [x] Update the OCP 4 App Migration Guide
 - [x] Prepare visual materials for an OCP 4 App Migration  Workshop ( to be run in Dec)

**Comment by jleach** [comment]
Notes from Todays Meeting:

- Check In
- Build Agenda
- Work Through Agenda

## Who is our Audience (ie. POs, TCs, etc)?

Developers a.k.a the DevOps person on a team. 
We can call this "OCP4 Migration Developer Workshop".

## What are the goals?

- Creating a library reusable assets (video) to address specific migration topics;
- Provide in-person support to teams;
- Expedite the migration process;
- Strengthen community who looks out for one another;

## How do we achieve our goals?

- Could we do this as a Lab? Where I keep a Zoom channel open all day and teams can
come and go for real time support as needed?
- We cold make this a "migration **day**" theme.
- Give an introduction; break out into smaller groups with. Consider a debrief.
- Option: Do a pre-workshop thing. Those who want to hand around for the full session then that would be
good.
- Option: Series of smaller workshops to accomplish starting with a foundation then smaller modules like:
-- What's new in OCP4.
-- Jenkens
-- Data Migration
-- Writing NSP
-- Kickof including a checklist of high value items.
- Option: Still hold in-person sessions as one of our goals is to have "community" but record them so that we
have a repeatable asset.
- We like short but high frequency meetings where teams can ask questions in person.
- Office hours will be daily with one or more SME from the P.S. team. (M, W, F 10-11A; T, Th 2-3P).

## Deliverables

1. Foundational kick-off (ribbon cutting) to a officially around the general availability of OCP4 and summarize the
lessons learnt during the early adopter meeting as well as provide a checklist for migration preparation (Dec 2);
-- Run an in-person meeting that will be recorded;
-- An accompanying slide deck with information and a checklist;
Included in the deck:
- Schedule (when you need to be off OCP3);
- What does success look like to a team?
- Remember to down services on OCP3 so we can reclaim resources.
- Remember to crow about your success.

2. Create a series of pre-recorded modules that cover a specific topic in detail (ie How to NSP,
Data Migration Considerations);

3. Migration Support Open Office Hours where teams can connect directly with a resident migration expert;

**Comment by jleach** [comment]
Topic List:

- [ ] Kickof including a checklist of high value items **Jason**
- [ ] What's new in OCP4.
- [ ] Jenkens
- [ ] Data Migration
- [ ] Writing NSP
- [ ] Don't forget Migration Considerations - port access and firewall requests.
- [ ] Would love a quick walk-through on how to effectively use Artifactory on OCP4. **Jason**
- [ ] Use backup container to backup data on V3 and restore it on V4
- [ ] Moving from RHEL7 to Universal Base Image
- [ ] And using the build entitlements for UBI/RHEL based images
- [ ] May be less important once Tekton arrives, but I'm sure teams out there who have been using Jenkinsfiles would appreciate content on how to port an "OCP3" style Jenkinsfile to "OCP4". There are lots of projects out there that have Jenkinsfiles from a year or more ago.

**Comment by jleach** [comment]
Meeting Notes Nov 30, 2020.
Olean, Bev, Jason.

- Jason to lead the workshop so the teams better know him (me);

## Workshop Adjenda 

- Timelines for migration: Dec 2 to Feb 26th, 2021; a migration is considered complete when the project set in OCP3.11 is shut down.
- We **will** shut the OCP3.11 cluster down as of Feb 26th. We need the servers to build capacity on OCP4 (Gold and Gold DR).
- Teams who don't move by then will be evicted by the P.S team and its not guaronteed to be a plesant migration. All your stuff will be in boxes on the curb.

## Introduciton

- How log has early access been going for (Oct 14th)
- How many teams are already on OCP4 (~60)?
- How many teams / project need to migrate (everyone, aproximatly 189)?
- Tell teams about helpful resources: GitHub QA and In-person meetings for two weeks.

## What's new in OCP4?

- Aporeto
- Artifactory
- OCP Console
- Minor technical changes such as new storage types, new network topology, some changes to YAML API, quota. All documented
in the migration repo (48 issues).

## Prerequesites (What can I do in advance)

- Read through the Q&A from the early access.
- Request firewall rules; (Point to OCP4 Network Topology Document in Protected Space of Documize)
Include link to documize here https://docs.pathfinder.gov.bc.ca/
- Plan your migraton
- - Do you have a DNS?
- - Data migration?

## Migration Best Practices (Pro Tips)

Add link to the QA topic in OCP4 migration repo.

## Where can I get help?

- We'll be running live help sessions with a migration expert on T, Th from 2:30-3:30pm and W at 10-11am. This will be your
opportunity to ask questions about your migration.
- You can also find help in our OCP4 Migration Q&A. (include link).
- RocketChat #devops-ocp4-migration
- Where can you give help? #devops-ocp4-migration and create a Q&A issue in the repo.

## What else do I need to know?

- We're goint to be upgrading to OCP4.6 in early January. As per usual all nodes will be impacted and we strongly
encourage teams to ensure their apps are designed to be resiliant (high-availability, multi note deployments).

- Once your migration is completd we need you to request your namespaces be shut down on OCP311. https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+mitovskaol%2C+ShellyXueHan&labels=openshift-project-set%2C+pending&template=openshift_project_request.md&title=

- How long will it take? Don't boil the ocean. Focus on migrating first, then do other tasks like refactoring or adding
new features. If you do this it should be doable in a week.

## How do I get started?

- Tell them about the registry. https://registry.developer.gov.bc.ca/public-landing
- Its expected the product owner submit the request. This will keep their projects visible on the dashboard and
encourage ownership.
- The entire team should read through the topics in the Q&A; they were created by the early adopters and have lots of valuble 
information to help you hit the ground running.


## Key Success Factors

- Communicate to the "business" that this work is importand and has needs prioritization;
- Circle back to the "business" when your work is completed to let them know you were sucessful;
- Complete the prerequeistes as soon as possible; iStore orders can take some time and the holidays are approactng quick.
- Take the time to make sure, when you migrate, your applicaiton is HA. https://developer.gov.bc.ca/Resiliency-Guidelines



## Action Items

- Luke to schedule the daily live help sessions w/ Teams Link. Starting week of Dec 8th and run until the holidays.
This should be set out just after the kick-off. Questions at the end.
- Luke to schedule the kick-off workshop. Done.
- Bev to draft the invite for the daily touch points.
- Olena to make chanel public.
- Jason to capture this ^ in a video that can be watched.
- Jason / Team to create a few short videos on the key points.
- Jason to Edit the the early access slide deck to reflect general availability; use a moving-day-theme.

**Comment by mitovskaol** [comment]
The Early Majority Migration Kick off meeting had place on Dec 2. Closing the Sprint Goal.
