### ISSUE TITLE
SG - Migrate Platform services apps to new SSO service name - oidc.gov.bc.ca

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#695]
## Summary

There are many platform service apps that still utilize the old SSO Service name sso.pathfinder.gov.bc.ca. We will need to change the configuration for those apps in accordance with our own service bulletin :) 

## To Do
Change sso configuration for the following apps:

- [x] devhub web
- [x] devhub api
- [x] rocketchat
- [x] documize
- [x] reggie web (depending on RC)
- [x] reggie api
- [x] realm o matic web
- [x] realm o matic api
- [x] realm o matic ansible

## Definition of Done

All apps have been migrated and utilize oidc.gov.bc.ca for their auth flows !

**Comment by ShellyXueHan** [comment]
### Update:
- all listed apps's SSO integration have been updated now
- after the team has identified all platform service namespaces, need to cross reference on the list of apps we manage and double check on any more apps that need change
