### ISSUE TITLE
Deploy Mautic on Openshift

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#710]
## Summary

After our spike on mautic it appears that it can be deployed on Openshift with some customization. The app itself is not OCP friendly but it looks like we can do some slight modifications to a docker image to make it more OCP friendly.

Some of the issues that we have found include:

- available docker image utilizes a specific user
- database information is passed via a gui wizard and not as configuration

## Tasks

- [ ] Create a new docker image that does not utilize a specific user when building/running mautic 
- [ ] Find a way to configure a database without having to utilize the mautic gui wizard (i think there actually is environment variables we can use)
- [ ] Create a SAML SSO client for mautic
- [ ] See if we can utilize argo in an appropriate ocp cluster to wrap our build and deploy of mautic in a pipeline :) 
- [ ] We need a namespace to build/deploy mautic 
- [ ] Document how to build/deploy mautic
- [ ] See if there are ways to contribute back to the mautic project with our work
