### ISSUE TITLE
Artifactory Pipeline Development

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#750]
**Describe the issue**
The completion of this issue should produce an initial version of a pipeline for Artifactory which is capable of installing and updating Artifactory and its Operator in both KLAB and Silver

**Additional context**
We are planning to use Argo, which is new to both of us, and so this process will include a lot of investigation into the specific ways that Argo works.

**Definition of done**
- [ ] Completed pipeline which can install and update Artifactory and its Operator
- [ ] Documentation outlining the way this particular pipeline works
- [ ] Generalized documentation on the use of Argo, for use by other teams

**Comment by caggles** [comment]
Hey @IanKWatts! This is the epic for the Artifactory pipeline - a lot of the tickets are about Argo, but they could be easily adjusted I think. Let's chat next week about this ticket and our instance of Artifactory so we both know how to proceed!

**Comment by IanKWatts** [comment]
Thanks @caggles , we'll talk next week.
