### ISSUE TITLE
SonarQube config investigation

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#957]
Desire for MISOs and Security teams to understand configurations and best practices for static code analysis using SonarQube.
While SonarCloud and CodeClimate are also used by teams, this ticket will only focus on SonarQube local pipeline implementation.
This ticket will NOT investigate dynamic analysis (e.g. OWASP ZAP).

This is to leverage the sample project on the Silver Cluster.

- [ ] Stand up SonarQube
- [ ] Investigate config options and best practices
- [ ] Perform scan(s)
- [ ] Validate configs
- [ ] Report back to ISAC
